In [ ]:
import h5py

with h5py.File('/content/sample_data/train.hdf5', 'r') as file:
    # Print all group names (keys) in the file
    def print_attrs(name, obj):
        print(name)

    file.visititems(print_attrs)



X
X/sequence
Y
Y/output
weights


In [ ]:
import h5py

with h5py.File('/content/sample_data/train.hdf5', 'r') as file:
    # List all groups and datasets
    def explore_structure(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(f"Dataset: {name}")
        elif isinstance(obj, h5py.Group):
            print(f"Group: {name}")

    file.visititems(explore_structure)


Group: X
Dataset: X/sequence
Group: Y
Dataset: Y/output
Group: weights


In [ ]:
with h5py.File('/content/sample_data/train.hdf5', 'r') as file:
    # Accessing the dataset 'sequence' under group 'X'
    sequence_data = file['X/sequence'][:]
    print("Sequence data:", sequence_data)

    # Accessing the dataset 'output' under group 'Y'
    output_data = file['Y/output'][:]
    print("Output data:", output_data)


Sequence data: [[[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]]
Output data: [[-1.8394496  -1.3714164  -1.860508   ... -0.48974192 -0.25042853
  -0.43638697]
 [-1.8394496  -1.3714164  -1.860508   ... -0.48974192 -0.25042853
  -0.43638697]
 [-0.6241887  -0.2483657  -0.49987984 ...  0.03345118 -1.8992287
  -1.1234441 ]
 ...
 [-0.8586054   1.5450506   0.45529526 ...  1.626769    0.5821582
   1.2992789 ]
 [ 0.7190142   

In [ ]:
with h5py.File('/content/sample_data/valid.hdf5', 'r') as file:
    # Accessing the dataset 'sequence' under group 'X'
    sequence_data = file['X/sequence'][:]
    print("Sequence data:", sequence_data)

    # Accessing the dataset 'output' under group 'Y'
    output_data = file['Y/output'][:]
    print("Output data:", output_data)

Sequence data: [[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 ...

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]]
Output data: [[-0.8249799  -1.5034798  -1.3725991  ...  0.05413565  0.02142959
   0.04447504]
 [-0.20448795 -0.53588045 -0.43909627 ...  0.20000751  0.3091786
   0.30273333]
 [-1.2717273   0.27968097 -0.5425013  ...  0.81941444  0.6830795
   0.889063  ]
 ...
 [ 0.5448266   0.92396593  0.8647128  ...  0.9470208   0.64274806
   0.9392275 ]
 [-1.9823563  -

In [ ]:
with h5py.File('/content/sample_data/test.hdf5', 'r') as file:
    # Accessing the dataset 'sequence' under group 'X'
    sequence_data = file['X/sequence'][:]
    print("Sequence data:", sequence_data)

    # Accessing the dataset 'output' under group 'Y'
    output_data = file['Y/output'][:]
    print("Output data:", output_data)

Sequence data: [[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 ...

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]]
Output data: [[-1.1480043  -1.559959   -1.5876448  ... -0.3099618  -0.28306702
  -0.3511585 ]
 [-2.178577   -0.78698003 -1.6963186  ...  0.0445888   0.20941071
   0.15203328]
 [ 1.2549686  -0.15427196  0.6090891  ...  0.6589449  -0.38040316
   0.15545247]
 ...
 [-1.5651194  -0.81297344 -1.3686457  ...  0.09077324 -0.03004333
   0.03487025]
 [-1.0637978 

In [ ]:
with h5py.File('/content/sample_data/train.hdf5', 'r') as file:
    weights_group = file['weights']

    # Print the contents of the 'weights' group
    for name in weights_group:
        print(f"Dataset or group in 'weights': {name}")

In [ ]:
with h5py.File('/content/sample_data/test.hdf5', 'r') as file:
    weights_group = file['weights']

    # Print the contents of the 'weights' group
    for name in weights_group:
        print(f"Dataset or group in 'weights': {name}")

In [ ]:
with h5py.File('/content/sample_data/valid.hdf5', 'r') as file:
    weights_group = file['weights']

    # Print the contents of the 'weights' group
    for name in weights_group:
        print(f"Dataset or group in 'weights': {name}")

In [ ]:
import sqlite3
from prettytable import PrettyTable

# Connect to the database
conn = sqlite3.connect('/content/sample_data/mprabase_v4_9.3.db')


cursor = conn.cursor()

# List all tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in the database:", tables)



Tables in the database: [('designed_library',), ('library_sequence',), ('element_score',), ('element_rep_score',), ('datasets',), ('sample',)]


In [ ]:
cursor.execute("PRAGMA table_info(designed_library);")
columns = cursor.fetchall()
pragma_headers = [desc[0] for desc in cursor.description]


column_table = PrettyTable()
column_table.field_names = pragma_headers

# Add rows of column info based on output)
for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)

# Fetch some data from the table
cursor.execute("SELECT * FROM designed_library LIMIT 20;")
rows = cursor.fetchall()
column_names = [description[0] for description in cursor.description]

data_table = PrettyTable()
data_table.field_names = column_names

for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+--------------------+------+---------+------------+----+
| cid |        name        | type | notnull | dflt_value | pk |
+-----+--------------------+------+---------+------------+----+
|  0  |     library_id     | TEXT |    1    |    None    | 1  |
|  1  |    library_name    | TEXT |    0    |    None    | 0  |
|  2  |    datasets_id     | TEXT |    1    |    None    | 0  |
|  3  | number_of_elements | TEXT |    0    |    None    | 0  |
+-----+--------------------+------+---------+------------+----+

Sample data:
+--------------+---------------------------------------------------+-------------+--------------------+
|  library_id  |                    library_name                   | datasets_id | number_of_elements |
+--------------+---------------------------------------------------+-------------+--------------------+
| DS0001-LID01 |             Cloned_array_oligo_library            |    DS0001   |        2440        |
| DS0021-LID01 | Klein_Cloned_array_

In [ ]:
cursor.execute("PRAGMA table_info(library_sequence);")
columns = cursor.fetchall()

pragma_headers = [desc[0] for desc in cursor.description]


column_table = PrettyTable()
column_table.field_names = pragma_headers

for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)


cursor.execute("SELECT * FROM library_sequence LIMIT 5;")
rows = cursor.fetchall()

column_names = [description[0] for description in cursor.description]


data_table = PrettyTable()
data_table.field_names = column_names

for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+----------------------+------+---------+------------+----+
| cid |         name         | type | notnull | dflt_value | pk |
+-----+----------------------+------+---------+------------+----+
|  0  |  library_element_id  | TEXT |    1    |    None    | 1  |
|  1  |      library_id      | TEXT |    1    |    None    | 0  |
|  2  |     genome_build     | TEXT |    0    |    None    | 0  |
|  3  |  element_coordinate  | TEXT |    0    |    None    | 0  |
|  4  | library_element_name | TEXT |    0    |    None    | 0  |
|  5  |       sequence       | TEXT |    0    |    None    | 0  |
+-----+----------------------+------+---------+------------+----+

Sample data:
+--------------------------+--------------+--------------+--------------------+----------------------------------------------------------------------+----------+
|    library_element_id    |  library_id  | genome_build | element_coordinate |                         library_element_name                  

In [ ]:
cursor.execute("PRAGMA table_info(element_score);")
columns = cursor.fetchall()


pragma_headers = [desc[0] for desc in cursor.description]

column_table = PrettyTable()
column_table.field_names = pragma_headers


for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)


cursor.execute("SELECT * FROM element_score LIMIT 5;")
rows = cursor.fetchall()


column_names = [description[0] for description in cursor.description]


data_table = PrettyTable()
data_table.field_names = column_names


for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+----------------------+------+---------+------------+----+
| cid |         name         | type | notnull | dflt_value | pk |
+-----+----------------------+------+---------+------------+----+
|  0  |  element_sample_id   | TEXT |    1    |    None    | 1  |
|  1  | library_element_name | TEXT |    0    |    None    | 0  |
|  2  |        score         | REAL |    1    |    None    | 0  |
|  3  |  library_element_id  | TEXT |    1    |    None    | 0  |
|  4  |      sample_id       | TEXT |    1    |    None    | 0  |
|  5  |      library_id      | TEXT |    1    |    None    | 0  |
+-----+----------------------+------+---------+------------+----+

Sample data:
+--------------------------+----------------------+--------------+--------------------------+--------------+--------------+
|    element_sample_id     | library_element_name |    score     |    library_element_id    |  sample_id   |  library_id  |
+--------------------------+----------------------+-----

In [ ]:
cursor.execute("PRAGMA table_info(element_rep_score);")
columns = cursor.fetchall()

pragma_headers = [desc[0] for desc in cursor.description]


column_table = PrettyTable()
column_table.field_names = pragma_headers


for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)

cursor.execute("SELECT * FROM element_rep_score LIMIT 5;")
rows = cursor.fetchall()


column_names = [description[0] for description in cursor.description]


data_table = PrettyTable()
data_table.field_names = column_names

for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+--------------------+------+---------+------------+----+
| cid |        name        | type | notnull | dflt_value | pk |
+-----+--------------------+------+---------+------------+----+
|  0  |   element_rep_id   | TEXT |    1    |    None    | 1  |
|  1  |     sample_id      | TEXT |    1    |    None    | 0  |
|  2  | library_element_id | TEXT |    1    |    None    | 0  |
|  3  |        REP1        | REAL |    0    |    None    | 0  |
|  4  |        REP2        | REAL |    0    |    None    | 0  |
|  5  |        REP3        | REAL |    0    |    None    | 0  |
|  6  |        REP4        | REAL |    0    |    None    | 0  |
|  7  |        REP5        | REAL |    0    |    None    | 0  |
|  8  |        REP6        | REAL |    0    |    None    | 0  |
|  9  |        REP7        | REAL |    0    |    None    | 0  |
|  10 |        REP8        | TEXT |    0    |    None    | 0  |
|  11 |        REP9        | TEXT |    0    |    None    | 0  |
|  12 |       REP1

In [ ]:
cursor.execute("PRAGMA table_info(datasets);")
columns = cursor.fetchall()


pragma_headers = [desc[0] for desc in cursor.description]


column_table = PrettyTable()
column_table.field_names = pragma_headers
for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)


cursor.execute("SELECT * FROM datasets LIMIT 5;")
rows = cursor.fetchall()

column_names = [description[0] for description in cursor.description]

data_table = PrettyTable()
data_table.field_names = column_names

for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+---------------+-------------+---------+------------+----+
| cid |      name     |     type    | notnull | dflt_value | pk |
+-----+---------------+-------------+---------+------------+----+
|  0  |  datasets_id  |     TEXT    |    1    |    None    | 1  |
|  1  | datasets_name |     TEXT    |    0    |    None    | 0  |
|  2  |      PMID     |     TEXT    |    0    |    None    | 0  |
|  3  |   GEO_number  | VARCHAR(10) |    0    |    None    | 0  |
|  4  |   SRP_number  |     TEXT    |    0    |    None    | 0  |
|  5  |   Reference   |     TEXT    |    0    |    None    | 0  |
|  6  |      labs     |     TEXT    |    0    |    None    | 0  |
+-----+---------------+-------------+---------+------------+----+

Sample data:
+-------------+--------------------+----------+------------+------------+----------------------------------------------------------------------------------------------------------------------+-----------------------------+
| datasets_id |

In [ ]:
cursor.execute("PRAGMA table_info(sample);")
columns = cursor.fetchall()

pragma_headers = [desc[0] for desc in cursor.description]

column_table = PrettyTable()
column_table.field_names = pragma_headers

for col in columns:
    column_table.add_row(col)

print("Columns in the table:")
print(column_table)


cursor.execute("SELECT * FROM sample LIMIT 5;")
rows = cursor.fetchall()

column_names = [description[0] for description in cursor.description]

data_table = PrettyTable()
data_table.field_names = column_names

for row in rows:
    data_table.add_row(row)

print("\nSample data:")
print(data_table)

Columns in the table:
+-----+------------------+------+---------+------------+----+
| cid |       name       | type | notnull | dflt_value | pk |
+-----+------------------+------+---------+------------+----+
|  0  |    sample_id     | TEXT |    1    |    None    | 1  |
|  1  |   sample_name    | TEXT |    0    |    None    | 0  |
|  2  | Library_strategy | TEXT |    0    |    None    | 0  |
|  3  |     Organism     | TEXT |    0    |    None    | 0  |
|  4  | Cell_line_tissue | TEXT |    0    |    None    | 0  |
|  5  |    library_id    | TEXT |    0    |    None    | 0  |
|  6  | element_position | TEXT |    0    |    None    | 0  |
|  7  |   DNA_RNA_reps   | TEXT |    0    |    None    | 0  |
|  8  |   description    | TEXT |    0    |    None    | 0  |
|  9  |  GenomeBrowser   | TEXT |    0    |    None    | 0  |
|  10 |     rep_type     | TEXT |    0    |    None    | 0  |
+-----+------------------+------+---------+------------+----+

Sample data:
+--------------+------------------

In [ ]:
!pip install zarr

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 69.4 MB/s eta 0:00:00
  Created wheel for asciitree: filename=asciitree-0.3.3-py3-none-any.whl size=5033 sha256=f1579146f65f32a30d1d3f1e79c0bd7eb71504bd24a4f81aed4e2ee51366e3a1
  Stored in directory: /root/.cache/pip/wheels/7f/4e/be/1171b40f43b918087657ec57cf3b81fa1a2e027d8755baa184
Successfully built asciitree


In [ ]:
import numpy as np
import zarr
from PIL import Image

image = Image.open('/content/drive/MyDrive/(09)-Pereyra2021A-BMCBioinformatics/DS0001/(F1)-ZStacks-Fusion-ZS/CH0001/DR(F1)/Pereyra2021A-DS0001TP0001DR(F1)CH0001PL(AS).TIF')

image_data = np.array(image)

# Create a .zarr store
zarr_store = zarr.open('/content/sample_data', mode='w', shape=image_data.shape, dtype=image_data.dtype)

zarr_store[:] = image_data


In [ ]:
import numpy as np
import zarr
from PIL import Image

image = Image.open('/content/drive/MyDrive/(09)-Pereyra2021A-BMCBioinformatics/DS0001/(F1)-ZStacks-Fusion-ZS/CH0001/DR(F1)/Pereyra2021A-DS0001TP0002DR(F1)CH0001PL(AS).TIF')

image_data = np.array(image)

# Create a .zarr store
zarr_store = zarr.open('/content/sample_data', mode='w', shape=image_data.shape, dtype=image_data.dtype)

zarr_store[:] = image_data
